fieldLayouts:
  9b2debe6-6023-49fc-90ec-32c293f33f3f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 5bde24cc-1f5e-414b-b7a3-6cca8212952b # SEO
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 1
handle: careerHome
hasTitleField: false
name: 'Career - Home'
section: 451c3f7d-d8da-4738-b52f-2dd7a98387c2 # Career - Home
sortOrder: 1
titleFormat: Career
titleTranslationKeyFormat: null
titleTranslationMethod: site
