fieldLayouts:
  315ffb7b-fd7c-42df-85f6-9655fbedd5bf:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 5bde24cc-1f5e-414b-b7a3-6cca8212952b # SEO
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: projectsHome
hasTitleField: false
name: 'Projects — Home'
section: 4623326c-9e72-4085-9777-e7347ad967d9 # Projects — Home
sortOrder: 1
titleFormat: Projects
titleTranslationKeyFormat: null
titleTranslationMethod: site
