fieldLayouts:
  1be0e5a7-6b0a-4e16-8d46-c3035bf38e4a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 02125f3f-c007-4194-8935-fb4a1f983544 # Project Link
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 8df94775-08e5-4a9c-8015-13c3af3c308f # Project Featured Image
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 29e89b01-2124-417b-a053-a978438fde63 # Date Completed
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 54bae388-6436-4719-a2e7-72fd7d7f7f7d # Project Employer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 478e3740-3f23-43d0-840b-de6d3942878e # Skills Used
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4212bd1d-2ac8-4b2d-a066-9b9ce38f9de8 # Project Description
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e70bc399-6474-44fd-a015-834a84ecba2e # Content Blocks
            instructions: 'Use this if you want to go more in depth in an article style. It will give you more control over media presented, to be quite honest.'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 5bde24cc-1f5e-414b-b7a3-6cca8212952b # SEO
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: projects
hasTitleField: true
name: Projects
section: 6398217c-4a0c-426c-924f-0d4047b910cf # Projects
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
