contentColumnType: string
fieldGroup: 08c3cece-baba-403b-b910-bcf82581a06b # Globals
handle: awards
instructions: ''
name: Awards
searchable: false
settings:
  contentTable: '{{%stc_awards}}'
  fieldLayout: row
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: 'Add an Award'
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
