columnSuffix: null
contentColumnType: string
fieldGroup: fab9a07f-4f19-4812-8169-70358d9aae7b # Common
handle: contentBlocks
instructions: ''
name: 'Content Blocks'
searchable: false
settings:
  contentTable: '{{%matrixcontent_contentblocks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
