defaultPlacement: end
enableVersioning: true
handle: careerHome
name: 'Career - Home'
propagationMethod: all
siteSettings:
  3b31166f-6db9-429f-8ed6-0c2c66424a07: # Kevin Amézaga
    enabledByDefault: true
    hasUrls: true
    template: career
    uriFormat: career
type: single
