enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  3b31166f-6db9-429f-8ed6-0c2c66424a07: # Kevin Amézaga
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
